---
- name: Add Jenkins YUM repository
  ansible.builtin.yum_repository:
    name: jenkins
    description: Jenkins-stable
    baseurl: https://pkg.jenkins.io/rpm-stable
    gpgcheck: yes
    gpgkey: https://pkg.jenkins.io/rpm-stable/repodata/repomd.xml.key
